name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: anymok/ubeer-back:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ env.DOCKER_HUB_PASSWORD }}